export const imageData=[
  
    {
      "id": 1,
      "src": "./src/assets/images/img1",
      "alt": "Design1",
      "designName": "Flower Power",
      "designerName": "Zuco",
      "avatar": "./src/assets/images/av1",
      "tags": ["yellow", "flower", "seed", "bright"],
      "categories": ["branding","web design","mobile"],
      "likes": 102,
      "views": "1.5k"
    },
    {
      "id": 2,
      "src": "./src/assets/images/img2",
      "alt": "Design2",
      "designName": "Ocean Breeze",
      "designerName": "Aqua",
      "avatar": "./src/assets/images/av2",
      "tags": ["blue", "ocean", "wave", "cool"],
      "categories": ["branding", "web design","print"],
      "likes": 87,
      "views": "4.5k",
    },
    {
      "id": 3,
      "src": "./src/assets/images/img3",
      "alt": "Design3",
      "designName": "Mountain Peak",
      "designerName": "Rocky",
      "avatar": "./src/assets/images/av3",
      "tags": ["mountain", "snow", "peak", "majestic","brown"],
      "categories": ["typography", "branding","print"],
      "likes": 20,
      "views": 180
    },
    {
      "id": 4,
      "src": "./src/assets/images/img4",
      "alt": "Design4",
      "designName": "City Lights",
      "designerName": "Urban",
      "avatar": "./src/assets/images/av4",
      "tags": ["green","city", "night", "lights", "bright"],
      "categories": ["web design", "illustration","print"],
      "likes": 454,
      "views": "2.2k"
    },
    {
      "id": 5,
      "src": "./src/assets/images/img5",
      "alt": "Design5",
      "designName": "Desert Mirage",
      "designerName": "Sandy",
      "avatar": "./src/assets/images/av6",
      "tags": ["brown","desert", "sunset", "mirage", "warm"],
      "categories": ["typography", "branding"],
      "likes": 65,
      "views": 450
    },
    {
      "id": 6,
      "src": "./src/assets/images/img6",
      "alt": "Design6",
      "designName": "Forest Whisper",
      "designerName": "Greenie",
      "avatar": "./src/assets/images/av7",
      "tags": ["green","forest", "trees", "whisper", "calm"],
      "categories": ["illustration", "branding"],
      "likes": 280,
      "views": "400"
    },
    {
      "id": 7,
      "src": "./src/assets/images/img7",
      "alt": "Design7",
      "designName": "Galaxy Quest",
      "designerName": "Star",
      "avatar": "./src/assets/images/av5",
      "tags": ["galaxy", "stars", "space", "infinite","blue"],
      "categories": ["animation", "web design","mobile","product design"],
      "likes": 35,
      "views": 275
    },
    {
      "id": 8,
      "src": "./src/assets/images/img8",
      "alt": "Design8",
      "designName": "Autumn Leaves",
      "designerName": "Leafy",
      "avatar": "./src/assets/images/av9",
      "tags": ["autumn", "leaves","green", "fall", "orange"],
      "categories": ["typography", "illustration","mobile"],
      "likes": 245,
      "views": "1.2k"
    },
    {
      "id": 9,
      "src": "./src/assets/images/img9",
      "alt": "Design9",
      "designName": "Winter Wonderland",
      "designerName": "Snowy",
      "avatar": "./src/assets/images/av8",
      "tags": ["winter", "snow", "wonderland", "white"],
      "categories": ["illustration", "branding","print"],
      "likes": 22,
      "views": 320
    },
    {
      "id": 10,
      "src": "./src/assets/images/img10",
      "alt": "Design10",
      "designName": "Sunrise Bliss",
      "designerName": "Dawn",
      "avatar": "./src/assets/images/av2",
      "tags": ["sunrise", "bliss", "morning","grey" ,"peaceful"],
      "categories": ["typography", "branding", "web design","mobile"],
      "likes": 560,
      "views": "5.8k"
    },
    {
      "id": 11,
      "src": "./src/assets/images/img11",
      "alt": "Design11",
      "designName": "Rainy Days",
      "designerName": "Stormy",
      "avatar": "./src/assets/images/av1",
      "tags": ["rain", "days", "grey", "calm"],
      "categories": ["illustration", "web design","typography","mobile"],
      "likes": 76,
      "views": 450
    },
    {
      "id": 12,
      "src": "./src/assets/images/img12",
      "alt": "Design12",
      "designName": "Spring Bloom",
      "designerName": "Flora",
      "avatar": "./src/assets/images/av4",
      "tags": ["spring", "bloom", "flowers", "colorful"],
      "categories": ["typography", "branding","mobile"],
      "likes": 390,
      "views": 870
    },
    {
      "id": 13,
      "src": "./src/assets/images/img13",
      "alt": "Design13",
      "designName": "Summer Vibes",
      "designerName": "Sunny",
      "avatar": "./src/assets/images/av5",
      "tags": ["summer", "vibes", "beach", "bright"],
      "categories": ["product design", "branding","print"],
      "likes": 34,
      "views": "3.2k"
    },
    {
      "id": 14,
      "src": "./src/assets/images/img14",
      "alt": "Design14",
      "designName": "Urban Jungle",
      "designerName": "City",
      "avatar": "./src/assets/images/av7",
      "tags": ["urban", "jungle", "city", "green"],
      "categories": ["illustration", "web design"],
      "likes": "993",
      "views": "9.5k"
    },
    {
      "id": 15,
      "src": "./src/assets/images/img15",
      "alt": "Design15",
      "designName": "Country Roads",
      "designerName": "Rural",
      "avatar": "./src/assets/images/av8",
      "tags": ["country", "roads", "fields", "peaceful"],
      "categories": ["typography", "branding"],
      "likes": 21,
      "views": 564
    },
    {
      "id": 16,
      "src": "./src/assets/images/img16",
      "alt": "Design16",
      "designName": "Mystic Mountains",
      "designerName": "Mystic",
      "avatar": "./src/assets/images/av4",
      "tags": ["mountains", "mist", "mystic", "cool","water"],
      "categories": ["illustration", "branding", "product design"],
      "likes": 98,
      "views": "4.3k"
    },
    {
      "id": 17,
      "src": "./src/assets/images/img17",
      "alt": "Design17",
      "designName": "Twilight Dreams",
      "designerName": "Dreamer",
      "avatar": "./src/assets/images/av1",
      "tags": ["twilight", "dreams", "purple", "calm"],
      "categories": ["animation", "web design","mobile"],
      "likes": 70,
      "views": "1.5k"
    },
    {
      "id": 18,
      "src": "./src/assets/images/img18",
      "alt": "Design18",
      "designName": "Cosmic Journey",
      "designerName": "Cosmo",
      "avatar": "./src/assets/images/av6",
      "tags": ["cosmic", "space", "journey", "stars"],
      "categories": ["animation", "illustration","product design","mobile"],
      "likes": 300,
      "views": "2.2k"
    },
    {
      "id": 19,
      "src": "./src/assets/images/img19",
      "alt": "Design19",
      "designName": "Rainforest Retreat",
      "designerName": "Rain",
      "avatar": "./src/assets/images/av2",
      "tags": ["rainforest", "green", "retreat", "nature"],
      "categories": ["typography", "branding" ,"product design"],
      "likes": 34,
      "views": 267
    },
    {
      "id": 20,
      "src": "./src/assets/images/img20",
      "alt": "Design20",
      "designName": "Zen Garden",
      "designerName": "Zen",
      "avatar": "./src/assets/images/av7",
      "tags": ["zen", "garden", "peaceful", "serene"],
      "categories": ["illustration", "web design","product design","mobile"],
      "likes": 16,
      "views": 467
    },
    {
      "id": 21,
      "src": "./src/assets/images/img21",
      "alt": "Design21",
      "designName": "Glacier Glow",
      "designerName": "Icey",
      "avatar": "./src/assets/images/av9",
      "tags": ["glacier", "ice", "glow", "cold"],
      "categories": ["branding", "illustration", "print"],
      "likes": 30,
      "views": 400
    },
    {
      "id": 22,
      "src": "./src/assets/images/img22",
      "alt": "Design22",
      "designName": "Lunar Eclipse",
      "designerName": "Luna",
      "avatar": "./src/assets/images/av3",
      "tags": ["lunar", "eclipse", "moon", "night"],
      "categories": ["animation", "web design","mobile"],
      "likes": 85,
      "views": 500
    },
    {
      "id": 23,
      "src": "./src/assets/images/img23",
      "alt": "Design23",
      "designName": "Tropical Paradise",
      "designerName": "Isla",
      "avatar": "./src/assets/images/av1",
      "tags": ["tropical", "paradise", "beach", "sun"],
      "categories": ["illustration", "branding", "product design"],
      "likes": 28,
      "views": 380
    },
    {
      "id": 24,
      "src": "./src/assets/images/img24",
      "alt": "Design24",
      "designName": "Meadow Song",
      "designerName": "Daisy",
      "avatar": "./src/assets/images/av5",
      "tags": ["meadow", "song", "flowers", "calm"],
      "categories": ["typography", "print"],
      "likes": 453,
      "views": 876
    },
    {
      "id": 25,
      "src": "./src/assets/images/img25",
      "alt": "Design25",
      "designName": "Aurora Sky",
      "designerName": "Aurora",
      "avatar": "./src/assets/images/av8",
      "tags": ["aurora", "sky", "northern lights", "colorful"],
      "categories": ["animation", "illustration", "web design"],
      "likes": 29,
      "views": 546
    },
    {
      "id": 26,
      "src": "./src/assets/images/img26",
      "alt": "Design26",
      "designName": "Sunny Meadow",
      "designerName": "Sunshine",
      "avatar": "./src/assets/images/av4",
      "tags": ["sunny", "meadow", "bright", "flowers"],
      "categories": ["illustration", "print", "branding"],
      "likes": 31,
      "views": 220
    },
    {
      "id": 27,
      "src": "./src/assets/images/img27",
      "alt": "Design27",
      "designName": "Mystic Forest",
      "designerName": "Enigma",
      "avatar": "./src/assets/images/av3",
      "tags": ["forest", "mystic", "trees", "green"],
      "categories": ["illustration", "web design", "animation"],
      "likes": 20,
      "views": 310
    },
    {
      "id": 28,
      "src": "./src/assets/images/img28",
      "alt": "Design28",
      "designName": "Enchanted Garden",
      "designerName": "Fae",
      "avatar": "./src/assets/images/av9",
      "tags": ["enchanted", "garden", "magic", "flowers"],
      "categories": ["illustration", "branding", "print", "product design"],
      "likes": 90,
      "views": "6.5k"
    },
    {
      "id": 29,
      "src": "./src/assets/images/img29",
      "alt": "Design29",
      "designName": "Starry Night",
      "designerName": "Vincent",
      "avatar": "./src/assets/images/av7",
      "tags": ["starry", "night", "stars", "sky"],
      "categories": ["illustration", "animation", "web design"],
      "likes": 31,
      "views": 410
    },
    {
      "id": 30,
      "src": "./src/assets/images/img30",
      "alt": "Design30",
      "designName": "Golden Fields",
      "designerName": "Harvest",
      "avatar": "./src/assets/images/av2",
      "tags": ["golden", "fields", "wheat", "sunset"],
      "categories": ["typography", "branding", "print", "product design"],
      "likes": 398,
      "views": "5.4k"
    },
    {
      "id": 31,
      "src": "./src/assets/images/img31",
      "alt": "Design31",
      "designName": "Crimson Sunset",
      "designerName": "Scarlet",
      "avatar": "./src/assets/images/av6",
      "tags": ["crimson", "sunset", "red", "warm"],
      "categories": ["branding", "print", "illustration"],
      "likes": 17,
      "views": 280
    },
    {
      "id": 32,
      "src": "./src/assets/images/img32",
      "alt": "Design32",
      "designName": "Celestial Dreams",
      "designerName": "Nova",
      "avatar": "./src/assets/images/av3",
      "tags": ["celestial", "dreams", "space", "stars","white"],
      "categories": ["animation", "web design", "product design"],
      "likes": 654,
      "views": "8.6k"
    }
  ]
  
